name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for finding/opening this issue! We will be working on it as soon as possible!"
        pr-message: "Excellent work! Remember to contact a reviewer and ensure your code follows the community guidelines"
